apiVersion: v1
kind: Service
metadata:
  name: app-portal-postgresql-service
spec:
  selector:
    app: app-portal-postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP