apiVersion: v1
kind: Secret
metadata:
  name: app-portal-secret
type: Opaque
data:
  .env: |
    PORT=3000
    SESSION_SECRET=my-very-secure-secret
    DATABASE_URL=postgresql://user:password@localhost:5432/portalDb
    ADMIN_USERNAME=admin
    ADMIN_PASSWORD=admin123